baseURL = 'https://chenminhua.github.io/'
languageCode = 'en-us'
title = '硕大的汤姆'
theme = 'ink-free'


[params]
	subtitle = "The official website of Minhua Chen"

	# Optional 64x64 avatar image.
	avatar = "https://avatars.githubusercontent.com/u/10234400?v=4"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	wpm = 250
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/knadh/hugo-ink"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
