baseURL = 'https://chenmh.fun/'
languageCode = 'en-us'
title = '硕大的汤姆'
theme = 'nostyleplease'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.41.0'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  description = 'The official website of Minhua Chen'

  [params.theme_config]
    appearance = 'auto'
    back_home_text = '← home'
    date_format = '2006-01-02'
    isListGroupByDate = false
    isShowFooter = false
    show_description = true

[taxonomies]
  tag = 'tags'
